### ISSUE TITLE
用 sfml.js + TypeScript？

### ISSUE THREAD

**Issue by XadillaX** [chinese-chess-everywhere/type-chess#1]
可以在桌面玩🙈

**Comment by luckyyyyy** [comment]
> > 额，想要能玩的话早就有了啊：
> > https://xufei.github.io/vue-chess/
> > 这次纯属恶搞，想挑战自我。。。
> 
> 主要是非 Web 版🙈

真会玩 今天刚看到 nodejs 插件封了 sfml 可以玩出花了
