### ISSUE TITLE
提前设定类型会发生什么？

### ISSUE THREAD

**Issue by AkatQuas** [chinese-chess-everywhere/type-chess#5]
https://github.com/chinese-chess-everywhere/type-chess/blob/9c04f3d459c0e2a010aa11c171ed7aaa008ed7fc/src/integer.ts#L75-L86

前面 `相等` 的设定时，会预先定义好两个参数的类型为 `相等<甲 extends 整数, 乙 extends 整数>` 。

那么这个 `由小到大排序`也能这么做吗？ 

```typescript
  type 数组 = [整数, 整数];
  // 不推荐前置设定类型，因为会破坏完备？
  export type 由小到大排序<元 extends 数组> = 大于<元[0], 元[1]> extends 是
    ? [元[1], 元[0]]
    : 元;
```

而现在的实现需要多一步 `infer` 数组的类型，这两种有什么区别呢？

**Comment by xufei** [comment]
你这样可以，因为我这个场景并不需要泛化，不存在有人故意传递不符合条件的数组进来，拦截这步其实无所谓
